// Code generated by ogen, DO NOT EDIT.

package tracker_v1

import (
	"net/http"

	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
)

// UpdateTrackerParams is parameters of updateTracker operation.
type UpdateTrackerParams struct {
	ID int
}

func unpackUpdateTrackerParams(packed middleware.Parameters) (params UpdateTrackerParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int)
	}
	return params
}

func decodeUpdateTrackerParams(args [0]string, argsEscaped bool, r *http.Request) (params UpdateTrackerParams, _ error) {
	// Decode path: id.
	if err := func() error {
		// Not used.
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
