// Code generated by ogen, DO NOT EDIT.

package tracker_v1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateTracker implements createTracker operation.
	//
	// Create new tracker.
	//
	// POST /trackers
	CreateTracker(ctx context.Context, req *CreateTrackerRequest) (CreateTrackerRes, error)
	// UpdateTracker implements updateTracker operation.
	//
	// Update tracker.
	//
	// PUT /trackers/{id}
	UpdateTracker(ctx context.Context, req *UpdateTrackerRequest, params UpdateTrackerParams) (UpdateTrackerRes, error)
	// NewError creates *GenericErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *GenericErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
