// Code generated by ogen, DO NOT EDIT.

package tracker_v1

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateTrackerOperation OperationName = "CreateTracker"
	UpdateTrackerOperation OperationName = "UpdateTracker"
)
