// Code generated by ogen, DO NOT EDIT.

package tracker_v1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateTracker implements createTracker operation.
//
// Create new tracker.
//
// POST /trackers
func (UnimplementedHandler) CreateTracker(ctx context.Context, req *CreateTrackerRequest) (r CreateTrackerRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateTracker implements updateTracker operation.
//
// Update tracker.
//
// PUT /trackers/{id}
func (UnimplementedHandler) UpdateTracker(ctx context.Context, req *UpdateTrackerRequest, params UpdateTrackerParams) (r UpdateTrackerRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *GenericErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *GenericErrorStatusCode) {
	r = new(GenericErrorStatusCode)
	return r
}
