openapi: 3.0.0
info:
  title: Order Service API
  description: Сервис заказов для космических кораблей
  version: 1.0.0
paths:
  /orders:
    post:
      summary: Create new order
      operationId: createOrder
      tags:
        - Orders
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/create_order_request'
      responses:
        '201':
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/create_order_response'
        '400':
          description: Bad request - validation errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/validation_error'
        '402':
          description: Payment calculation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_gateway_error'
        '409':
          description: Invalid parts or order conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/conflict_error'
        '500':
          description: Internal server errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_server_error'
        '503':
          description: Inventory service unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/service_unavailable_error'
        default:
          description: Unexpected errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/generic_error'
  /orders/{order_uuid}:
    get:
      summary: Get order by UUID
      operationId: getOrder
      tags:
        - Orders
      parameters:
        - $ref: '#/components/parameters/order_uuid'
      responses:
        '200':
          description: Order information retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/get_order_response'
        '400':
          description: Bad request - validation errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_request_error'
        '404':
          description: Order not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/not_found_error'
        '500':
          description: Internal server errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_server_error'
        default:
          description: Unexpected errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/generic_error'
  /orders/{order_uuid}/pay:
    post:
      summary: Pay for order
      operationId: payOrder
      tags:
        - Orders
      parameters:
        - $ref: '#/components/parameters/order_uuid'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/pay_order_request'
      responses:
        '200':
          description: Payment processed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pay_order_response'
        '400':
          description: Bad request - validation errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/validation_error'
        '402':
          description: Payment failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_request_error'
        '404':
          description: Order not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/not_found_error'
        '409':
          description: Order already paid or cancelled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/conflict_error'
        '500':
          description: Internal server errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_server_error'
        '502':
          description: Payment service errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_gateway_error'
        '503':
          description: Payment service unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/service_unavailable_error'
        default:
          description: Unexpected errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/generic_error'
  /orders/{order_uuid}/cancel:
    post:
      summary: Cancel order
      operationId: cancelOrder
      tags:
        - Orders
      parameters:
        - $ref: '#/components/parameters/order_uuid'
      responses:
        '204':
          description: Order cancelled successfully
        '404':
          description: Order not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/not_found_error'
        '409':
          description: Cannot cancel paid order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/conflict_error'
        '500':
          description: Internal server errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_server_error'
        default:
          description: Unexpected errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/generic_error'
components:
  schemas:
    CreateOrderRequest:
      $ref: '#/components/schemas/create_order_request'
    CreateOrderResponse:
      $ref: '#/components/schemas/create_order_response'
    GetOrderResponse:
      $ref: '#/components/schemas/get_order_response'
    OrderDTO:
      $ref: '#/components/schemas/order_dto'
    PayOrderRequest:
      $ref: '#/components/schemas/pay_order_request'
    PayOrderResponse:
      $ref: '#/components/schemas/pay_order_response'
    OrderStatus:
      $ref: '#/components/schemas/order_status'
    PaymentMethod:
      $ref: '#/components/schemas/payment_method'
    GenericError:
      $ref: '#/components/schemas/generic_error'
    BadRequestError:
      $ref: '#/components/schemas/bad_request_error'
    ValidationError:
      $ref: '#/components/schemas/validation_error'
    NotFoundError:
      $ref: '#/components/schemas/not_found_error'
    ConflictError:
      $ref: '#/components/schemas/conflict_error'
    InternalServerError:
      $ref: '#/components/schemas/internal_server_error'
    BadGatewayError:
      $ref: '#/components/schemas/bad_gateway_error'
    ServiceUnavailableError:
      $ref: '#/components/schemas/service_unavailable_error'
    UnauthorizedError:
      $ref: '#/components/schemas/unauthorized_error'
    ForbiddenError:
      $ref: '#/components/schemas/forbidden_error'
    RateLimitError:
      $ref: '#/components/schemas/rate_limit_error'
    create_order_request:
      type: object
      properties:
        user_uuid:
          type: string
          format: uuid
          description: UUID пользователя
          example: 123e4567-e89b-12d3-a456-426614174000
        part_uuids:
          type: array
          items:
            type: string
            format: uuid
          description: Список UUID деталей для заказа
          example:
            - 123e4567-e89b-12d3-a456-426614174001
            - 123e4567-e89b-12d3-a456-426614174002
      required:
        - user_uuid
        - part_uuids
    generic_error:
      type: object
      properties:
        error:
          type: string
          description: Тип ошибки
        code:
          type: integer
          description: HTTP статус код
        message:
          type: string
          description: Сообщение об ошибке
        details:
          type: array
          items:
            type: string
          description: Дополнительные детали ошибки
        request_id:
          type: string
          description: Идентификатор запроса для отслеживания
      required:
        - errors
        - code
        - message
    create_order_response:
      type: object
      properties:
        order_uuid:
          type: string
          format: uuid
          description: UUID созданного заказа
          example: 123e4567-e89b-12d3-a456-426614174000
        total_price:
          type: number
          format: double
          description: Общая стоимость заказа
          example: 123.45
      required:
        - order_uuid
        - total_price
    validation_error:
      type: object
      properties:
        error:
          type: string
          example: VALIDATION_ERROR
        code:
          type: integer
          example: 400
        message:
          type: string
          example: Ошибка валидации данных
        fields:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
                description: Поле с ошибкой
              message:
                type: string
                description: Сообщение об ошибке
              value:
                type: string
                description: Некорректное значение
          description: Список полей с ошибками валидации
        details:
          type: array
          items:
            type: string
        request_id:
          type: string
    bad_gateway_error:
      type: object
      properties:
        error:
          type: string
          example: BAD_GATEWAY
        code:
          type: integer
          example: 502
        message:
          type: string
          example: Ошибка взаимодействия с внешним сервисом
        service:
          type: string
          description: Название внешнего сервиса
        operation:
          type: string
          description: Выполняемая операция
        details:
          type: array
          items:
            type: string
        request_id:
          type: string
    conflict_error:
      type: object
      properties:
        error:
          type: string
          example: CONFLICT
        code:
          type: integer
          example: 409
        message:
          type: string
          example: Конфликт состояния ресурса
        resource_type:
          type: string
          description: Тип ресурса
        resource_id:
          type: string
          description: Идентификатор ресурса
        current_state:
          type: string
          description: Текущее состояние
        required_state:
          type: string
          description: Требуемое состояние
        details:
          type: array
          items:
            type: string
        request_id:
          type: string
    internal_server_error:
      type: object
      properties:
        error:
          type: string
          example: INTERNAL_SERVER_ERROR
        code:
          type: integer
          example: 500
        message:
          type: string
          example: Внутренняя ошибка сервера
        details:
          type: array
          items:
            type: string
        request_id:
          type: string
          description: Идентификатор для отслеживания ошибки
    service_unavailable_error:
      type: object
      properties:
        error:
          type: string
          example: SERVICE_UNAVAILABLE
        code:
          type: integer
          example: 503
        message:
          type: string
          example: Сервис временно недоступен
        service:
          type: string
          description: Название сервиса
        retry_after:
          type: integer
          description: Время через которое можно повторить запрос (секунды)
        details:
          type: array
          items:
            type: string
        request_id:
          type: string
    order_status:
      type: object
      properties:
        orderStatus:
          type: string
          enum:
            - PENDING_PAYMENT
            - PAID
            - CANCELLED
          description: |
            Способы оплаты:
            - PENDING_PAYMENT: Заказ создан, ожидается оплата
            - PAID: Заказ оплачен и подтвержден
            - CANCELLED: Заказ отменен (истекло время оплаты или отмена пользователем)
          example: PAID
    get_order_response:
      type: object
      properties:
        order_uuid:
          type: string
          format: uuid
          description: UUID заказа
        user_uuid:
          type: string
          format: uuid
          description: UUID пользователя
        part_uuids:
          type: array
          items:
            type: string
            format: uuid
          description: Список UUID деталей
        total_price:
          type: number
          format: double
          description: Общая стоимость
        transaction_uuid:
          type: string
          format: uuid
          description: UUID транзакции (если оплачен)
          nullable: true
        payment_method:
          type: string
          description: Способ оплаты
          nullable: true
        status:
          type: string
          description: Статус заказа
          $ref: '#/components/schemas/order_status'
      required:
        - order_uuid
        - user_uuid
        - part_uuids
        - total_price
        - status
    bad_request_error:
      type: object
      properties:
        error:
          type: string
          example: BAD_REQUEST
        code:
          type: integer
          example: 400
        message:
          type: string
          example: Неверный запрос
        details:
          type: array
          items:
            type: string
        request_id:
          type: string
    not_found_error:
      type: object
      properties:
        error:
          type: string
          example: NOT_FOUND
        code:
          type: integer
          example: 404
        message:
          type: string
          example: Ресурс не найден
        resource_type:
          type: string
          description: Тип ресурса (order, part, user)
        resource_id:
          type: string
          description: Идентификатор ресурса
        details:
          type: array
          items:
            type: string
        request_id:
          type: string
    payment_method:
      type: object
      properties:
        PaymentMethod:
          type: integer
          enum:
            - 0
            - 1
            - 2
            - 3
            - 4
          description: |
            Способы оплаты:
            - 0: Неизвестный способ
            - 1: Банковская карта
            - 2: Система быстрых платежей
            - 3: Кредитная карта
            - 4: Деньги инвестора
          example: 1
    pay_order_request:
      type: object
      properties:
        payment_method:
          type: string
          description: Способ оплаты
          $ref: '#/components/schemas/payment_method'
          example: CARD
      required:
        - payment_method
    pay_order_response:
      type: object
      properties:
        transaction_uuid:
          type: string
          format: uuid
          description: UUID транзакции
          example: 123e4567-e89b-12d3-a456-426614174000
      required:
        - transaction_uuid
    order_dto:
      type: object
      required:
        - order_uuid
        - user_uuid
        - part_uuids
        - total_price
        - status
      properties:
        order_uuid:
          type: string
          format: uuid
          description: UUID заказа
        user_uuid:
          type: string
          format: uuid
          description: UUID пользователя
        part_uuids:
          type: array
          items:
            type: string
            format: uuid
          description: Список UUID деталей
        total_price:
          type: number
          format: double
          description: Общая стоимость
        transaction_uuid:
          type: string
          format: uuid
          description: UUID транзакции
          nullable: true
        payment_method:
          type: string
          description: Способ оплаты
          nullable: true
        status:
          type: string
          description: Статус заказа
          $ref: '#/components/schemas/order_status'
    unauthorized_error:
      type: object
      properties:
        error:
          type: string
          example: UNAUTHORIZED
        code:
          type: integer
          example: 401
        message:
          type: string
          example: Требуется аутентификация
        details:
          type: array
          items:
            type: string
        request_id:
          type: string
    forbidden_error:
      type: object
      properties:
        error:
          type: string
          example: FORBIDDEN
        code:
          type: integer
          example: 403
        message:
          type: string
          example: Доступ запрещен
        details:
          type: array
          items:
            type: string
        request_id:
          type: string
    rate_limit_error:
      type: object
      properties:
        error:
          type: string
          example: RATE_LIMIT_EXCEEDED
        code:
          type: integer
          example: 429
        message:
          type: string
          example: Превышен лимит запросов
        limit:
          type: integer
          description: Лимит запросов
        period:
          type: string
          description: Период лимита
        retry_after:
          type: integer
          description: Время через которое можно повторить запрос (секунды)
        details:
          type: array
          items:
            type: string
        request_id:
          type: string
  parameters:
    OrderUuid:
      $ref: '#/components/parameters/order_uuid'
    order_uuid:
      name: order_uuid
      in: path
      required: true
      description: Уникальный идентификатор для order
      schema:
        type: string
        format: uuid
        example: 550e8400-e29b-41d4-a716-446655440000
