// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"fmt"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

func (s *GenericErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/bad_gateway_error
type BadGatewayError struct {
	Error   OptString `json:"error"`
	Code    OptInt    `json:"code"`
	Message OptString `json:"message"`
	// Название внешнего сервиса.
	Service OptString `json:"service"`
	// Выполняемая операция.
	Operation OptString `json:"operation"`
	Details   []string  `json:"details"`
	RequestID OptString `json:"request_id"`
}

// GetError returns the value of Error.
func (s *BadGatewayError) GetError() OptString {
	return s.Error
}

// GetCode returns the value of Code.
func (s *BadGatewayError) GetCode() OptInt {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *BadGatewayError) GetMessage() OptString {
	return s.Message
}

// GetService returns the value of Service.
func (s *BadGatewayError) GetService() OptString {
	return s.Service
}

// GetOperation returns the value of Operation.
func (s *BadGatewayError) GetOperation() OptString {
	return s.Operation
}

// GetDetails returns the value of Details.
func (s *BadGatewayError) GetDetails() []string {
	return s.Details
}

// GetRequestID returns the value of RequestID.
func (s *BadGatewayError) GetRequestID() OptString {
	return s.RequestID
}

// SetError sets the value of Error.
func (s *BadGatewayError) SetError(val OptString) {
	s.Error = val
}

// SetCode sets the value of Code.
func (s *BadGatewayError) SetCode(val OptInt) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *BadGatewayError) SetMessage(val OptString) {
	s.Message = val
}

// SetService sets the value of Service.
func (s *BadGatewayError) SetService(val OptString) {
	s.Service = val
}

// SetOperation sets the value of Operation.
func (s *BadGatewayError) SetOperation(val OptString) {
	s.Operation = val
}

// SetDetails sets the value of Details.
func (s *BadGatewayError) SetDetails(val []string) {
	s.Details = val
}

// SetRequestID sets the value of RequestID.
func (s *BadGatewayError) SetRequestID(val OptString) {
	s.RequestID = val
}

func (*BadGatewayError) createOrderRes() {}
func (*BadGatewayError) payOrderRes()    {}

// Ref: #/components/schemas/bad_request_error
type BadRequestError struct {
	Error     OptString `json:"error"`
	Code      OptInt    `json:"code"`
	Message   OptString `json:"message"`
	Details   []string  `json:"details"`
	RequestID OptString `json:"request_id"`
}

// GetError returns the value of Error.
func (s *BadRequestError) GetError() OptString {
	return s.Error
}

// GetCode returns the value of Code.
func (s *BadRequestError) GetCode() OptInt {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *BadRequestError) GetMessage() OptString {
	return s.Message
}

// GetDetails returns the value of Details.
func (s *BadRequestError) GetDetails() []string {
	return s.Details
}

// GetRequestID returns the value of RequestID.
func (s *BadRequestError) GetRequestID() OptString {
	return s.RequestID
}

// SetError sets the value of Error.
func (s *BadRequestError) SetError(val OptString) {
	s.Error = val
}

// SetCode sets the value of Code.
func (s *BadRequestError) SetCode(val OptInt) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *BadRequestError) SetMessage(val OptString) {
	s.Message = val
}

// SetDetails sets the value of Details.
func (s *BadRequestError) SetDetails(val []string) {
	s.Details = val
}

// SetRequestID sets the value of RequestID.
func (s *BadRequestError) SetRequestID(val OptString) {
	s.RequestID = val
}

func (*BadRequestError) getOrderRes() {}
func (*BadRequestError) payOrderRes() {}

// CancelOrderNoContent is response for CancelOrder operation.
type CancelOrderNoContent struct{}

func (*CancelOrderNoContent) cancelOrderRes() {}

// Ref: #/components/schemas/conflict_error
type ConflictError struct {
	Error   OptString `json:"error"`
	Code    OptInt    `json:"code"`
	Message OptString `json:"message"`
	// Тип ресурса.
	ResourceType OptString `json:"resource_type"`
	// Идентификатор ресурса.
	ResourceID OptString `json:"resource_id"`
	// Текущее состояние.
	CurrentState OptString `json:"current_state"`
	// Требуемое состояние.
	RequiredState OptString `json:"required_state"`
	Details       []string  `json:"details"`
	RequestID     OptString `json:"request_id"`
}

// GetError returns the value of Error.
func (s *ConflictError) GetError() OptString {
	return s.Error
}

// GetCode returns the value of Code.
func (s *ConflictError) GetCode() OptInt {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ConflictError) GetMessage() OptString {
	return s.Message
}

// GetResourceType returns the value of ResourceType.
func (s *ConflictError) GetResourceType() OptString {
	return s.ResourceType
}

// GetResourceID returns the value of ResourceID.
func (s *ConflictError) GetResourceID() OptString {
	return s.ResourceID
}

// GetCurrentState returns the value of CurrentState.
func (s *ConflictError) GetCurrentState() OptString {
	return s.CurrentState
}

// GetRequiredState returns the value of RequiredState.
func (s *ConflictError) GetRequiredState() OptString {
	return s.RequiredState
}

// GetDetails returns the value of Details.
func (s *ConflictError) GetDetails() []string {
	return s.Details
}

// GetRequestID returns the value of RequestID.
func (s *ConflictError) GetRequestID() OptString {
	return s.RequestID
}

// SetError sets the value of Error.
func (s *ConflictError) SetError(val OptString) {
	s.Error = val
}

// SetCode sets the value of Code.
func (s *ConflictError) SetCode(val OptInt) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ConflictError) SetMessage(val OptString) {
	s.Message = val
}

// SetResourceType sets the value of ResourceType.
func (s *ConflictError) SetResourceType(val OptString) {
	s.ResourceType = val
}

// SetResourceID sets the value of ResourceID.
func (s *ConflictError) SetResourceID(val OptString) {
	s.ResourceID = val
}

// SetCurrentState sets the value of CurrentState.
func (s *ConflictError) SetCurrentState(val OptString) {
	s.CurrentState = val
}

// SetRequiredState sets the value of RequiredState.
func (s *ConflictError) SetRequiredState(val OptString) {
	s.RequiredState = val
}

// SetDetails sets the value of Details.
func (s *ConflictError) SetDetails(val []string) {
	s.Details = val
}

// SetRequestID sets the value of RequestID.
func (s *ConflictError) SetRequestID(val OptString) {
	s.RequestID = val
}

func (*ConflictError) cancelOrderRes() {}
func (*ConflictError) createOrderRes() {}
func (*ConflictError) payOrderRes()    {}

// Ref: #/components/schemas/create_order_request
type CreateOrderRequest struct {
	// UUID пользователя.
	UserUUID uuid.UUID `json:"user_uuid"`
	// Список UUID деталей для заказа.
	PartUuids []uuid.UUID `json:"part_uuids"`
}

// GetUserUUID returns the value of UserUUID.
func (s *CreateOrderRequest) GetUserUUID() uuid.UUID {
	return s.UserUUID
}

// GetPartUuids returns the value of PartUuids.
func (s *CreateOrderRequest) GetPartUuids() []uuid.UUID {
	return s.PartUuids
}

// SetUserUUID sets the value of UserUUID.
func (s *CreateOrderRequest) SetUserUUID(val uuid.UUID) {
	s.UserUUID = val
}

// SetPartUuids sets the value of PartUuids.
func (s *CreateOrderRequest) SetPartUuids(val []uuid.UUID) {
	s.PartUuids = val
}

// Ref: #/components/schemas/create_order_response
type CreateOrderResponse struct {
	// UUID созданного заказа.
	OrderUUID uuid.UUID `json:"order_uuid"`
	// Общая стоимость заказа.
	TotalPrice float64 `json:"total_price"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *CreateOrderResponse) GetOrderUUID() uuid.UUID {
	return s.OrderUUID
}

// GetTotalPrice returns the value of TotalPrice.
func (s *CreateOrderResponse) GetTotalPrice() float64 {
	return s.TotalPrice
}

// SetOrderUUID sets the value of OrderUUID.
func (s *CreateOrderResponse) SetOrderUUID(val uuid.UUID) {
	s.OrderUUID = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *CreateOrderResponse) SetTotalPrice(val float64) {
	s.TotalPrice = val
}

func (*CreateOrderResponse) createOrderRes() {}

// Ref: #/components/schemas/generic_error
type GenericError struct {
	// Тип ошибки.
	Error OptString `json:"error"`
	// HTTP статус код.
	Code int `json:"code"`
	// Сообщение об ошибке.
	Message string `json:"message"`
	// Дополнительные детали ошибки.
	Details []string `json:"details"`
	// Идентификатор запроса для отслеживания.
	RequestID OptString `json:"request_id"`
}

// GetError returns the value of Error.
func (s *GenericError) GetError() OptString {
	return s.Error
}

// GetCode returns the value of Code.
func (s *GenericError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *GenericError) GetMessage() string {
	return s.Message
}

// GetDetails returns the value of Details.
func (s *GenericError) GetDetails() []string {
	return s.Details
}

// GetRequestID returns the value of RequestID.
func (s *GenericError) GetRequestID() OptString {
	return s.RequestID
}

// SetError sets the value of Error.
func (s *GenericError) SetError(val OptString) {
	s.Error = val
}

// SetCode sets the value of Code.
func (s *GenericError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *GenericError) SetMessage(val string) {
	s.Message = val
}

// SetDetails sets the value of Details.
func (s *GenericError) SetDetails(val []string) {
	s.Details = val
}

// SetRequestID sets the value of RequestID.
func (s *GenericError) SetRequestID(val OptString) {
	s.RequestID = val
}

// GenericErrorStatusCode wraps GenericError with StatusCode.
type GenericErrorStatusCode struct {
	StatusCode int
	Response   GenericError
}

// GetStatusCode returns the value of StatusCode.
func (s *GenericErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *GenericErrorStatusCode) GetResponse() GenericError {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *GenericErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *GenericErrorStatusCode) SetResponse(val GenericError) {
	s.Response = val
}

// Ref: #/components/schemas/get_order_response
type GetOrderResponse struct {
	// UUID заказа.
	OrderUUID uuid.UUID `json:"order_uuid"`
	// UUID пользователя.
	UserUUID uuid.UUID `json:"user_uuid"`
	// Список UUID деталей.
	PartUuids []uuid.UUID `json:"part_uuids"`
	// Общая стоимость.
	TotalPrice float64 `json:"total_price"`
	// UUID транзакции (если оплачен).
	TransactionUUID OptNilUUID `json:"transaction_uuid"`
	// Способ оплаты.
	PaymentMethod OptNilString `json:"payment_method"`
	// Статус заказа.
	Status OrderStatus `json:"status"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *GetOrderResponse) GetOrderUUID() uuid.UUID {
	return s.OrderUUID
}

// GetUserUUID returns the value of UserUUID.
func (s *GetOrderResponse) GetUserUUID() uuid.UUID {
	return s.UserUUID
}

// GetPartUuids returns the value of PartUuids.
func (s *GetOrderResponse) GetPartUuids() []uuid.UUID {
	return s.PartUuids
}

// GetTotalPrice returns the value of TotalPrice.
func (s *GetOrderResponse) GetTotalPrice() float64 {
	return s.TotalPrice
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *GetOrderResponse) GetTransactionUUID() OptNilUUID {
	return s.TransactionUUID
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *GetOrderResponse) GetPaymentMethod() OptNilString {
	return s.PaymentMethod
}

// GetStatus returns the value of Status.
func (s *GetOrderResponse) GetStatus() OrderStatus {
	return s.Status
}

// SetOrderUUID sets the value of OrderUUID.
func (s *GetOrderResponse) SetOrderUUID(val uuid.UUID) {
	s.OrderUUID = val
}

// SetUserUUID sets the value of UserUUID.
func (s *GetOrderResponse) SetUserUUID(val uuid.UUID) {
	s.UserUUID = val
}

// SetPartUuids sets the value of PartUuids.
func (s *GetOrderResponse) SetPartUuids(val []uuid.UUID) {
	s.PartUuids = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *GetOrderResponse) SetTotalPrice(val float64) {
	s.TotalPrice = val
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *GetOrderResponse) SetTransactionUUID(val OptNilUUID) {
	s.TransactionUUID = val
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *GetOrderResponse) SetPaymentMethod(val OptNilString) {
	s.PaymentMethod = val
}

// SetStatus sets the value of Status.
func (s *GetOrderResponse) SetStatus(val OrderStatus) {
	s.Status = val
}

func (*GetOrderResponse) getOrderRes() {}

// Ref: #/components/schemas/internal_server_error
type InternalServerError struct {
	Error   OptString `json:"error"`
	Code    OptInt    `json:"code"`
	Message OptString `json:"message"`
	Details []string  `json:"details"`
	// Идентификатор для отслеживания ошибки.
	RequestID OptString `json:"request_id"`
}

// GetError returns the value of Error.
func (s *InternalServerError) GetError() OptString {
	return s.Error
}

// GetCode returns the value of Code.
func (s *InternalServerError) GetCode() OptInt {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *InternalServerError) GetMessage() OptString {
	return s.Message
}

// GetDetails returns the value of Details.
func (s *InternalServerError) GetDetails() []string {
	return s.Details
}

// GetRequestID returns the value of RequestID.
func (s *InternalServerError) GetRequestID() OptString {
	return s.RequestID
}

// SetError sets the value of Error.
func (s *InternalServerError) SetError(val OptString) {
	s.Error = val
}

// SetCode sets the value of Code.
func (s *InternalServerError) SetCode(val OptInt) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *InternalServerError) SetMessage(val OptString) {
	s.Message = val
}

// SetDetails sets the value of Details.
func (s *InternalServerError) SetDetails(val []string) {
	s.Details = val
}

// SetRequestID sets the value of RequestID.
func (s *InternalServerError) SetRequestID(val OptString) {
	s.RequestID = val
}

func (*InternalServerError) cancelOrderRes() {}
func (*InternalServerError) createOrderRes() {}
func (*InternalServerError) getOrderRes()    {}
func (*InternalServerError) payOrderRes()    {}

// Ref: #/components/schemas/not_found_error
type NotFoundError struct {
	Error   OptString `json:"error"`
	Code    OptInt    `json:"code"`
	Message OptString `json:"message"`
	// Тип ресурса (order, part, user).
	ResourceType OptString `json:"resource_type"`
	// Идентификатор ресурса.
	ResourceID OptString `json:"resource_id"`
	Details    []string  `json:"details"`
	RequestID  OptString `json:"request_id"`
}

// GetError returns the value of Error.
func (s *NotFoundError) GetError() OptString {
	return s.Error
}

// GetCode returns the value of Code.
func (s *NotFoundError) GetCode() OptInt {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *NotFoundError) GetMessage() OptString {
	return s.Message
}

// GetResourceType returns the value of ResourceType.
func (s *NotFoundError) GetResourceType() OptString {
	return s.ResourceType
}

// GetResourceID returns the value of ResourceID.
func (s *NotFoundError) GetResourceID() OptString {
	return s.ResourceID
}

// GetDetails returns the value of Details.
func (s *NotFoundError) GetDetails() []string {
	return s.Details
}

// GetRequestID returns the value of RequestID.
func (s *NotFoundError) GetRequestID() OptString {
	return s.RequestID
}

// SetError sets the value of Error.
func (s *NotFoundError) SetError(val OptString) {
	s.Error = val
}

// SetCode sets the value of Code.
func (s *NotFoundError) SetCode(val OptInt) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *NotFoundError) SetMessage(val OptString) {
	s.Message = val
}

// SetResourceType sets the value of ResourceType.
func (s *NotFoundError) SetResourceType(val OptString) {
	s.ResourceType = val
}

// SetResourceID sets the value of ResourceID.
func (s *NotFoundError) SetResourceID(val OptString) {
	s.ResourceID = val
}

// SetDetails sets the value of Details.
func (s *NotFoundError) SetDetails(val []string) {
	s.Details = val
}

// SetRequestID sets the value of RequestID.
func (s *NotFoundError) SetRequestID(val OptString) {
	s.RequestID = val
}

func (*NotFoundError) cancelOrderRes() {}
func (*NotFoundError) getOrderRes()    {}
func (*NotFoundError) payOrderRes()    {}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilUUID returns new OptNilUUID with value set to v.
func NewOptNilUUID(v uuid.UUID) OptNilUUID {
	return OptNilUUID{
		Value: v,
		Set:   true,
	}
}

// OptNilUUID is optional nullable uuid.UUID.
type OptNilUUID struct {
	Value uuid.UUID
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilUUID was set.
func (o OptNilUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilUUID) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilUUID) SetToNull() {
	o.Set = true
	o.Null = true
	var v uuid.UUID
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilUUID) Get() (v uuid.UUID, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptOrderStatusOrderStatus returns new OptOrderStatusOrderStatus with value set to v.
func NewOptOrderStatusOrderStatus(v OrderStatusOrderStatus) OptOrderStatusOrderStatus {
	return OptOrderStatusOrderStatus{
		Value: v,
		Set:   true,
	}
}

// OptOrderStatusOrderStatus is optional OrderStatusOrderStatus.
type OptOrderStatusOrderStatus struct {
	Value OrderStatusOrderStatus
	Set   bool
}

// IsSet returns true if OptOrderStatusOrderStatus was set.
func (o OptOrderStatusOrderStatus) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptOrderStatusOrderStatus) Reset() {
	var v OrderStatusOrderStatus
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptOrderStatusOrderStatus) SetTo(v OrderStatusOrderStatus) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptOrderStatusOrderStatus) Get() (v OrderStatusOrderStatus, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptOrderStatusOrderStatus) Or(d OrderStatusOrderStatus) OrderStatusOrderStatus {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPaymentMethodPaymentMethod returns new OptPaymentMethodPaymentMethod with value set to v.
func NewOptPaymentMethodPaymentMethod(v PaymentMethodPaymentMethod) OptPaymentMethodPaymentMethod {
	return OptPaymentMethodPaymentMethod{
		Value: v,
		Set:   true,
	}
}

// OptPaymentMethodPaymentMethod is optional PaymentMethodPaymentMethod.
type OptPaymentMethodPaymentMethod struct {
	Value PaymentMethodPaymentMethod
	Set   bool
}

// IsSet returns true if OptPaymentMethodPaymentMethod was set.
func (o OptPaymentMethodPaymentMethod) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPaymentMethodPaymentMethod) Reset() {
	var v PaymentMethodPaymentMethod
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPaymentMethodPaymentMethod) SetTo(v PaymentMethodPaymentMethod) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPaymentMethodPaymentMethod) Get() (v PaymentMethodPaymentMethod, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPaymentMethodPaymentMethod) Or(d PaymentMethodPaymentMethod) PaymentMethodPaymentMethod {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v

}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/order_status
type OrderStatus struct {
	// Способы оплаты:
	// - PENDING_PAYMENT: Заказ создан, ожидается оплата
	// - PAID: Заказ оплачен и подтвержден
	// - CANCELLED: Заказ отменен (истекло время оплаты или отмена
	// пользователем).
	OrderStatus OptOrderStatusOrderStatus `json:"orderStatus"`
}

// GetOrderStatus returns the value of OrderStatus.
func (s *OrderStatus) GetOrderStatus() OptOrderStatusOrderStatus {
	return s.OrderStatus
}

// SetOrderStatus sets the value of OrderStatus.
func (s *OrderStatus) SetOrderStatus(val OptOrderStatusOrderStatus) {
	s.OrderStatus = val
}

// Способы оплаты:
// - PENDING_PAYMENT: Заказ создан, ожидается оплата
// - PAID: Заказ оплачен и подтвержден
// - CANCELLED: Заказ отменен (истекло время оплаты или отмена
// пользователем).
type OrderStatusOrderStatus string

const (
	OrderStatusOrderStatusPENDINGPAYMENT OrderStatusOrderStatus = "PENDING_PAYMENT"
	OrderStatusOrderStatusPAID           OrderStatusOrderStatus = "PAID"
	OrderStatusOrderStatusCANCELLED      OrderStatusOrderStatus = "CANCELLED"
)

// AllValues returns all OrderStatusOrderStatus values.
func (OrderStatusOrderStatus) AllValues() []OrderStatusOrderStatus {
	return []OrderStatusOrderStatus{
		OrderStatusOrderStatusPENDINGPAYMENT,
		OrderStatusOrderStatusPAID,
		OrderStatusOrderStatusCANCELLED,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OrderStatusOrderStatus) MarshalText() ([]byte, error) {
	switch s {
	case OrderStatusOrderStatusPENDINGPAYMENT:
		return []byte(s), nil
	case OrderStatusOrderStatusPAID:
		return []byte(s), nil
	case OrderStatusOrderStatusCANCELLED:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OrderStatusOrderStatus) UnmarshalText(data []byte) error {
	switch OrderStatusOrderStatus(data) {
	case OrderStatusOrderStatusPENDINGPAYMENT:
		*s = OrderStatusOrderStatusPENDINGPAYMENT
		return nil
	case OrderStatusOrderStatusPAID:
		*s = OrderStatusOrderStatusPAID
		return nil
	case OrderStatusOrderStatusCANCELLED:
		*s = OrderStatusOrderStatusCANCELLED
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/pay_order_request
type PayOrderRequest struct {
	// Способ оплаты.
	PaymentMethod PaymentMethod `json:"payment_method"`
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *PayOrderRequest) GetPaymentMethod() PaymentMethod {
	return s.PaymentMethod
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *PayOrderRequest) SetPaymentMethod(val PaymentMethod) {
	s.PaymentMethod = val
}

// Ref: #/components/schemas/pay_order_response
type PayOrderResponse struct {
	// UUID транзакции.
	TransactionUUID uuid.UUID `json:"transaction_uuid"`
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *PayOrderResponse) GetTransactionUUID() uuid.UUID {
	return s.TransactionUUID
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *PayOrderResponse) SetTransactionUUID(val uuid.UUID) {
	s.TransactionUUID = val
}

func (*PayOrderResponse) payOrderRes() {}

// Ref: #/components/schemas/payment_method
type PaymentMethod struct {
	// Способы оплаты:
	// - 0: Неизвестный способ
	// - 1: Банковская карта
	// - 2: Система быстрых платежей
	// - 3: Кредитная карта
	// - 4: Деньги инвестора.
	PaymentMethod OptPaymentMethodPaymentMethod `json:"PaymentMethod"`
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *PaymentMethod) GetPaymentMethod() OptPaymentMethodPaymentMethod {
	return s.PaymentMethod
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *PaymentMethod) SetPaymentMethod(val OptPaymentMethodPaymentMethod) {
	s.PaymentMethod = val
}

// Способы оплаты:
// - 0: Неизвестный способ
// - 1: Банковская карта
// - 2: Система быстрых платежей
// - 3: Кредитная карта
// - 4: Деньги инвестора.
type PaymentMethodPaymentMethod int

const (
	PaymentMethodPaymentMethod0 PaymentMethodPaymentMethod = 0
	PaymentMethodPaymentMethod1 PaymentMethodPaymentMethod = 1
	PaymentMethodPaymentMethod2 PaymentMethodPaymentMethod = 2
	PaymentMethodPaymentMethod3 PaymentMethodPaymentMethod = 3
	PaymentMethodPaymentMethod4 PaymentMethodPaymentMethod = 4
)

// AllValues returns all PaymentMethodPaymentMethod values.
func (PaymentMethodPaymentMethod) AllValues() []PaymentMethodPaymentMethod {
	return []PaymentMethodPaymentMethod{
		PaymentMethodPaymentMethod0,
		PaymentMethodPaymentMethod1,
		PaymentMethodPaymentMethod2,
		PaymentMethodPaymentMethod3,
		PaymentMethodPaymentMethod4,
	}
}

// Ref: #/components/schemas/service_unavailable_error
type ServiceUnavailableError struct {
	Error   OptString `json:"error"`
	Code    OptInt    `json:"code"`
	Message OptString `json:"message"`
	// Название сервиса.
	Service OptString `json:"service"`
	// Время через которое можно повторить запрос (секунды).
	RetryAfter OptInt    `json:"retry_after"`
	Details    []string  `json:"details"`
	RequestID  OptString `json:"request_id"`
}

// GetError returns the value of Error.
func (s *ServiceUnavailableError) GetError() OptString {
	return s.Error
}

// GetCode returns the value of Code.
func (s *ServiceUnavailableError) GetCode() OptInt {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ServiceUnavailableError) GetMessage() OptString {
	return s.Message
}

// GetService returns the value of Service.
func (s *ServiceUnavailableError) GetService() OptString {
	return s.Service
}

// GetRetryAfter returns the value of RetryAfter.
func (s *ServiceUnavailableError) GetRetryAfter() OptInt {
	return s.RetryAfter
}

// GetDetails returns the value of Details.
func (s *ServiceUnavailableError) GetDetails() []string {
	return s.Details
}

// GetRequestID returns the value of RequestID.
func (s *ServiceUnavailableError) GetRequestID() OptString {
	return s.RequestID
}

// SetError sets the value of Error.
func (s *ServiceUnavailableError) SetError(val OptString) {
	s.Error = val
}

// SetCode sets the value of Code.
func (s *ServiceUnavailableError) SetCode(val OptInt) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ServiceUnavailableError) SetMessage(val OptString) {
	s.Message = val
}

// SetService sets the value of Service.
func (s *ServiceUnavailableError) SetService(val OptString) {
	s.Service = val
}

// SetRetryAfter sets the value of RetryAfter.
func (s *ServiceUnavailableError) SetRetryAfter(val OptInt) {
	s.RetryAfter = val
}

// SetDetails sets the value of Details.
func (s *ServiceUnavailableError) SetDetails(val []string) {
	s.Details = val
}

// SetRequestID sets the value of RequestID.
func (s *ServiceUnavailableError) SetRequestID(val OptString) {
	s.RequestID = val
}

func (*ServiceUnavailableError) createOrderRes() {}
func (*ServiceUnavailableError) payOrderRes()    {}

// Ref: #/components/schemas/validation_error
type ValidationError struct {
	Error   OptString `json:"error"`
	Code    OptInt    `json:"code"`
	Message OptString `json:"message"`
	// Список полей с ошибками валидации.
	Fields    []ValidationErrorFieldsItem `json:"fields"`
	Details   []string                    `json:"details"`
	RequestID OptString                   `json:"request_id"`
}

// GetError returns the value of Error.
func (s *ValidationError) GetError() OptString {
	return s.Error
}

// GetCode returns the value of Code.
func (s *ValidationError) GetCode() OptInt {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ValidationError) GetMessage() OptString {
	return s.Message
}

// GetFields returns the value of Fields.
func (s *ValidationError) GetFields() []ValidationErrorFieldsItem {
	return s.Fields
}

// GetDetails returns the value of Details.
func (s *ValidationError) GetDetails() []string {
	return s.Details
}

// GetRequestID returns the value of RequestID.
func (s *ValidationError) GetRequestID() OptString {
	return s.RequestID
}

// SetError sets the value of Error.
func (s *ValidationError) SetError(val OptString) {
	s.Error = val
}

// SetCode sets the value of Code.
func (s *ValidationError) SetCode(val OptInt) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ValidationError) SetMessage(val OptString) {
	s.Message = val
}

// SetFields sets the value of Fields.
func (s *ValidationError) SetFields(val []ValidationErrorFieldsItem) {
	s.Fields = val
}

// SetDetails sets the value of Details.
func (s *ValidationError) SetDetails(val []string) {
	s.Details = val
}

// SetRequestID sets the value of RequestID.
func (s *ValidationError) SetRequestID(val OptString) {
	s.RequestID = val
}

func (*ValidationError) createOrderRes() {}
func (*ValidationError) payOrderRes()    {}

type ValidationErrorFieldsItem struct {
	// Поле с ошибкой.
	Field OptString `json:"field"`
	// Сообщение об ошибке.
	Message OptString `json:"message"`
	// Некорректное значение.
	Value OptString `json:"value"`
}

// GetField returns the value of Field.
func (s *ValidationErrorFieldsItem) GetField() OptString {
	return s.Field
}

// GetMessage returns the value of Message.
func (s *ValidationErrorFieldsItem) GetMessage() OptString {
	return s.Message
}

// GetValue returns the value of Value.
func (s *ValidationErrorFieldsItem) GetValue() OptString {
	return s.Value
}

// SetField sets the value of Field.
func (s *ValidationErrorFieldsItem) SetField(val OptString) {
	s.Field = val
}

// SetMessage sets the value of Message.
func (s *ValidationErrorFieldsItem) SetMessage(val OptString) {
	s.Message = val
}

// SetValue sets the value of Value.
func (s *ValidationErrorFieldsItem) SetValue(val OptString) {
	s.Value = val
}
